main: me.rayzr522.itemframegiver.ItemFrameGiver
name: ItemFrameGiver
version: 1.0.0
description: Allows you to create item frames that give you items with a configurable cooldown
author: Rayzr
#commands:
#  itemframegiver:
#    description: The main command for ItemFrameGiver
#    aliases: [alias1,alias2]
#    usage: "\u00A7cRayzr fracked something up."